#!/usr/bin/env ruby
require 'rubygems'
require 'hpricot'
require 'open-uri'
require 'cgi'

# I hid the URL, because who knows who would be searching through my scripts!
url = CGI.unescape('%68%74%74%70%3a%2f%2f%74%68%65%66%75%63%6b%69%6e%67%77%65%61%74%68%65%72%2e%63%6f%6d%2f')
str = (Hpricot(open(url))/'.large').html.strip.sub('&deg;','º')
puts str.gsub(/<[^>]+>/,'#').gsub(/#+/,' - ').sub(/\s+\-\s+$/,'')
