#!/usr/bin/env ruby
# Start Date: March 16, 2008
# Updated: Tuesday May 20, 2008
# Current Version: 1.1
# Author: Joseph Pecoraro
# Contact: joepeck02@gmail.com
# Decription: "tidys" an xml file

# For each command line provided filename
# 1. Get entire data
# 2. Put into an XML Document
# 3. Print to STDOUT with 2 space indents for tags
# 4. Follow with a newline
require 'rexml/document'

if ARGV.size > 0
  ARGV.each do |filename|
    REXML::Document.new( File.new(filename).read ).write($stdout,2)
  end
else
  REXML::Document.new( STDIN.readlines.to_s ).write($stdout,2)
end
puts
